import { Typography, Stack, TextField, Button, Box, Alert } from "@mui/material";
import {
  Select,
  FormControl,
  InputLabel,
  MenuItem,
  OutlinedInput,
  Chip,
} from "@mui/material";
import React, { useEffect, useState } from "react";
import Home from "./Home";

const MAJORS = [
  "Accountancy",
  "Accountancy + Data Science",
  "ACES Undeclared",
  "Acting",
  "Actuarial Science",
  "Advertising",
  "Aerospace Engineering",
  "African American Studies",
  "Agri-Accounting",
  "Agribusiness, Markets & Management",
  "Agricultural and Biological Engineering (ACES)",
  "Agricultural and Biological Engineering (ENG)",
  "Agricultural and Consumer Economics",
  "Agricultural Communications",
  "Agricultural Education",
  "Agricultural Leadership, Education, and Communications",
  "Agronomy",
  "Animal Sciences",
  "Anthropology",
  "Architectural Studies",
  "Art and Art History ",
  "Art Education (K-12)",
  "Art Undeclared ",
  "Arts and Entertainment Technology ",
  "Asian American Studies",
  "Astronomy",
  "Astronomy + Data Science",
  "Astrophysics",
  "Atmospheric Sciences",
  "Biochemistry",
  "Bioengineering",
  "Biology",
  "Brain and Cognitive Science",
  "Business Undeclared",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Classics",
  "Communication",
  "Community Health",
  "Comparative and World Literature",
  "Computer Engineering",
  "Computer Science",
  "Computer Science and Advertising",
  "Computer Science and Animal Sciences",
  "Computer Science and Anthropology",
  "Computer Science and Astronomy",
  "Computer Science and Chemistry",
  "Computer Science and Crop Sciences",
  "Computer Science and Economics ",
  "Computer Science and Education, Learning Sciences",
  "Computer Science and Education, Secondary Education",
  "Computer Science and Geography & Geographic Information Science",
  "Computer Science and Linguistics",
  "Computer Science and Music",
  "Computer Science and Philosophy",
  "Consumer Economics & Finance",
  "Costume Design and Technology",
  "Creative Writing",
  "Crop Sciences",
  "Dance (BA)",
  "Dance (BFA)",
  "Dance, BA and Kinesiology, BS (Dual Degree Program)",
  "Dietetics",
  "Early Childhood Education (Birth-Grade 2)",
  "Earth, Society, and Environmental Sustainability",
  "East Asian Languages and Cultures",
  "Econometrics and Quantitative Economics",
  "Economics",
  "Electrical Engineering",
  "Elementary Education (Grades 1-6)",
  "Engineering Mechanics",
  "Engineering Technology and Management for Agricultural Systems",
  "Engineering Undeclared",
  "English",
  "Environmental Economics & Policy",
  "Farm Management",
  "Finance",
  "Finance + Data Science",
  "Finance in Agri-Business",
  "Financial Planning",
  "Food Science",
  "Food Science & Human Nutrition",
  "French",
  "Gender and Women's Studies",
  "Geography and Geographic Information Science",
  "Geology",
  "Germanic Studies",
  "Global Studies",
  "Graphic Design",
  "Health Sciences, Interdisciplinary ",
  "History",
  "History of Art",
  "Hospitality Management",
  "Human Development and Family Studies",
  "Human Nutrition",
  "Industrial Design",
  "Industrial Engineering",
  "Information Sciences",
  "Information Sciences + Data Science",
  "Information Systems",
  "Integrative Biology",
  "Interdisciplinary Studies",
  "Italian",
  "Jazz Performance",
  "Journalism",
  "Kinesiology",
  "Landscape Architecture ",
  "Latin American Studies",
  "Latina/Latino Studies",
  "Learning and Education Studies",
  "Lighting Design and Technology ",
  "Linguistics",
  "Linguistics and Teaching English as a Second Language",
  "Lyric Theatre",
  "Management",
  "Marketing",
  "Materials Science and Engineering",
  "Mathematics",
  "Mathematics and Computer Science",
  "Mechanical Engineering",
  "Media and Cinema Studies",
  "Metropolitan Food and Environmental Systems",
  "Middle Grades Education (Grades 5-8)",
  "Molecular and Cellular Biology",
  "Music",
  "Music Composition ",
  "Music Education (K-12)",
  "Music Instrumental Performance",
  "Music Open Studies",
  "Music Voice Performance",
  "Musicology",
  "Natural Resources and Environmental Sciences",
  "Neural Engineering",
  "Neuroscience",
  "Nuclear, Plasma, and Radiological Engineering",
  "Operations Management",
  "Organizational and Community Leadership",
  "Philosophy",
  "Physics",
  "Plant Biotechnology",
  "Policy, International Trade & Development",
  "Political Science",
  "Portuguese",
  "Psychology",
  "Public Policy & Law",
  "Recreation, Sport and Tourism",
  "Religion",
  "Russian, East European, and Eurasian Studies",
  "Scenic Design",
  "Scenic Technology",
  "Secondary Education",
  "Secondary Education: Biology",
  "Secondary Education: Chemistry",
  "Secondary Education: Earth Science",
  "Secondary Education: English ",
  "Secondary Education: Mathematics",
  "Secondary Education: Mathematics (LAS)",
  "Secondary Education: Physics",
  "Secondary Education: Social Studies",
  "Slavic Studies",
  "Social Work",
  "Sociology",
  "Sound Design and Technology",
  "Spanish",
  "Special Education",
  "Speech and Hearing Science",
  "Stage Management",
  "Statistics",
  "Statistics and Computer Science",
  "Strategy, Innovation and Entrepreneurship",
  "Studio Art (BA)",
  "Studio Art (BFA)",
  "Supply Chain Management",
  "Sustainable Design",
  "Systems Engineering and Design ",
  "Teacher Education: French (K-12)",
  "Teacher Education: German (K-12)",
  "Teacher Education: Kinesiology - Physical Education (K-12)",
  "Teacher Education: Spanish (K-12)",
  "Theatre Studies",
  "Undeclared",
  "Urban Studies and Planning",
];

const INTERESTS = [
  "Powerlifting",
  "Soccer",
  "Basketball",
  "Football",
  "Badminton",
  "Tennis",
  "Table Tennis",
  "Running",
  "Cycling",
];

const RSOList = [
  "Association of Computing Machinery",
  "Asian American Association",
  "Illini Esports",
  "iRobotics",
  "Cricket Club of Illinois",
  "Engineering Council",
  "Illini Biliards Club",
  "Illini Kendo Club",
  "Illini Powerlifting Club",
  "K-Project",
  "Men's Club Soccer",
  "Disruption Lab",
];

const CLASSES = [
  "Intro Asian American Studies",
  "Intro to Asian Am Pop Culture",
  "U.S. Race and Empire",
  "Intro Agric & Biological Engrg",
  "ABE Principles: Soil & Water",
  "Context Intl Interventions",
  "Project Management",
  "Renewable Energy Systems",
  "Bioprocessing Biomass for Fuel",
  "Graduate Research I",
  "Fundamentals of Accounting",
  "Accounting and Accountancy I",
  "Accounting and Accountancy II",
  "Atg Measurement & Disclosure",
  "Decision Making for Atg",
  "Atg Institutions and Reg",
  "Accounting Control Systems",
  "Principles of Taxation",
  "Practical Problems in Atg",
  "Assurance and Attestation",
  "Advanced Financial Reporting",
  "Advanced Income Tax Problems",
  "Atg Measuremnt, Rpting & Cntrl",
  "Accounting Analysis I A",
  "Accounting Analysis I B",
  "Accounting Analysis II",
  "Accounting Analysis II A",
  "Accounting Analysis II B",
  "Managerial Accounting",
  "Auditing",
  "Auditing A",
  "Auditing B",
  "Federal Taxation",
  "Federal Taxation A",
  "Federal Taxation B",
  "Financial Reporting Standards",
  "Auditing & Assurance Standards",
  "Financial Statement Analysis",
  "Corporate Income Taxation",
  "Tax Research",
  "Data Driven Decisions in Acctg",
  "Data Analytics Foundations",
  "ACCY Analytics Appl - A",
  "ACCY Analytics Appl - B",
  "Intro to Applied Micro",
  "Microcomputer Applications",
  "Digital Mktg and Social Media",
  "Negotiation",
  "Introduction to Sales",
  "Intro to Public Policy & Law",
  "Environmental Economics",
  "Agricultural Marketing",
  "Personal Financial Planning",
  "The World Food Economy",
  "Applied Statistical Methods",
  "App Stat Mthds & Data AnlytcsI",
  "App Stat Mthds & Data Anlytcs2",
  "Interm. Applied Microeconomics",
  "Natural Resource Economics",
  "Issues in Agribus Mkts & Mgmt",
  "Issues in Cons Econ & Finance",
  "Contemp Issue Comm Fin Plng",
  "Issues in AgAccy and FinAg",
  "Finan Decision Indiv Sm Bus",
  "Tax Policy and Finan Planning",
  "Risk Mngmt in Personal Fin Pla",
  "Environmental Law",
  "Environment and Development",
  "Commodity Price Analysis",
  "Commodity Futures and Options",
  "Global Agribusiness Management",
  "Finan Serv & Invest Plan",
  "Int Personal Fin & Estate Plan",
  "Intl Trade in Food and Agr",
  "Econ of Consumption",
  "Behavioral Economics",
  "Contemporary Issues in ACES",
  "History of Ag in IL Since 1860",
  "Introduction to Advertising",
  "Principles of Sales",
  "Advertising Research Methods",
  "Advertising and Brand Strategy",
  "Consumer Insight",
  "Becoming an Influencer",
  "Sports Public Relations",
  "Digital ADV Content",
  "Intro to Public Relations",
  "Classic Campaigns",
  "Sales Management",
  "Sales and the Consumer",
  "Content Creation",
  "Advertising and Society",
  "Media Entrepreneurship",
  "Innovation in Advertising",
  "Audience Analysis",
  "The Sandage Project",
  "Intro to Aerospace Engineering",
  "CAD",
  "Design, Build, Fly",
  "Introduction to Rocketry",
  "Aerospace Flight Mechanics",
  "Incompressible Flow",
  "Mechs of Aerospace Structures",
  "Applied Aerospace Structures",
  "Aerospace Dynamical Systems",
  "Aerospace Control Systems",
  "Orbital Mechanics",
  "Applied Aerodynamics",
  "Aerospace Propulsion",
  "Aerospace Systems Design I",
  "Aerodynamics & Propulsion Lab",
  "Autonomous Systems Lab",
  "Applied CFD",
  "Hypersonic AeroThermodynamics",
  "Planetary Entry",
  "Intro to African American St",
  "Black America, 1619-Present",
  "African American Music",
  "Black Women Contemp US Society",
  "Pan Africanism",
  "Hist of Blk Women's Activism",
  "African American Psychology",
  "Communicating Agriculture",
  "James Scholars Seminar",
  "Undergraduate Open Seminar",
  "Disability & Assistive Technol",
  "Intro to Amer Indian Studies",
  "Intro to American Indian Lit",
  "Intro to ALEC",
  "Professional Dev in ALEC",
  "Intro to Animal Sciences",
  "Working With Farm Animals",
  "Life With Animals and Biotech",
  "World Animal Resources",
  "Horse Management",
  "Science of Pets and Their Care",
  "Grilling and BBQ Science",
  "Cells, Metabolism and Genetics",
  "Anatomy and Physiology",
  "Companion Animals in Society",
  "Epidemics & Infectious Disease",
  "Animal Ethics",
  "Horse's Role in Human History",
  "Undergraduate Seminar",
  "Human Animal Interactions",
  "Companion Animal Management",
  "Meat Production and Marketing",
  "Cellular Metabolism in Animals",
  "CC Humane Society Internship",
  "Beef Production",
  "Companion Animal Nutrition",
  "Pet Food & Feed Manufacturing",
  "Advanced Reproductive Biology",
  "Statistical Methods",
  "Animal Growth and Development",
  "Integrating Animal Sciences",
  "Introduction to Anthropology",
  "Human Origins and Culture",
  "Anthro in a Changing World",
  "World Archaeology",
  "Hist Arch Americas",
  "Biology of Human Behavior",
  "Race & Contemporary Issues",
  "The Archaeology of Death",
  "Introduction to Archaeology",
  "Human Biological Variation",
  "Forensic Science",
  "Women's Lives",
  "Climate Change & Civilization",
  "Human Osteology",
  "Evolutionary Immunology",
  "Senior Capstone Seminar",
  "Lang&Culture of Arab World",
  "Concepts & Theories Arch Dsgn",
  "Intro Hist of World Arch",
  "Anatomy of Buildings",
  "Strategies of Arch Design",
  "Environ, Arch & Global Health",
  "Medieval Architecture",
  "Modern & Contemp Architecture",
  "Des of Steel and Reinf Conc I",
  "Environ Control Systems I",
  "Plng & Design of Struct Sys",
  "Theories of Architecture",
  "Graphic Design Toolbox",
  "Design Methods",
  "Human-Centered Product Design",
  "Product Innovation",
  "EDGE",
  "Contemporary Issues in Art",
  "Modern Art, 1880-1940",
  "American Art",
  "Graffiti and Murals",
  "Chado (The Way of Tea)",
  "Seminar in Japanese Aesthetics",
  "Manga: Art of Image and Word",
  "Introduction to Fashion",
  "Intro to Actuarial Science",
  "Theory of Interest",
  "Lin Algebra & Financial Apps",
  "Investments and Fin Markets",
  "Loss Models",
  "Casualty Actuarial Mathematics",
  "Life Contingencies I",
  "Introduction to Astronomy",
  "Solar System and Worlds Beyond",
  "Stars and Galaxies",
  "Killer Skies: Astro-Disasters",
  "Introduction to Astrophysics",
  "Big Bang,Black Holes,Universe",
  "Stellar Astrophysics",
  "Galaxies and the Universe",
  "Introduction to Meteorology",
  "Severe and Hazardous Weather",
  "Climate and Global Change",
  "Computing and Data Analysis",
  "Business Analytics I",
  "Business Analytics II",
  "Technology & Mgmt Seminar",
  "Operations Management",
  "The Legal Environment of Bus",
  "Mgmt and Organizational Beh",
  "Strategic Human Res Management",
  "Leading Negotiations",
  "Principles of Marketing",
  "Principles of Retailing",
  "Marketing Research",
  "Marketing Communications",
  "Purchasing and Supply Mgmnt",
  "Consumer Behavior",
  "Pricing Strategy",
  "New Product Development",
  "Supply Chain Management Basics",
  "Modeling the Supply Chain",
  "Ethical Dilemmas of Business",
  "IT for Networked Organizations",
  "Social Media Strategy",
  "Database Design and Management",
  "Info Sys Analysis and Design",
  "Data Science and Analytics",
  "New Product Marketing",
  "Mgmt of Innov and Technology",
  "Management Decision Models",
  "Operations Strategy",
  "Logistics Management",
  "International Business",
  "Multinational Management",
  "Entrep: New Venture Creation",
  "Business Policy and Strategy",
  "Business Intelligence",
  "IT Governance",
  "Business Process Modeling",
  "Communicating with Data",
  "Leadership and Teams",
  "Managing Organizations",
  "Communication Strategy in Bus",
  "Managing Innovation",
  "Marketing Management",
  "Frontiers in Technology",
  "Business Practicum",
  "Enterprise Database Management",
  "Supply Chain Management",
  "Process Management",
  "Stat for Mgt Decision Making",
  "Negotiations",
  "Intro to Brain & Cognitive Sci",
  "South Slavic Cultures",
  "Data Storytelling",
  "Biochemistry Senior Seminar",
  "Introduction to Bioengineering",
  "Conservation Principles Bioeng",
  "Cell & Tissue Engineering Lab",
  "Cellular Bioengineering",
  "Modeling Human Physiology",
  "Biomedical Instrumentation",
  "Biomedical Instrumentation Lab",
  "Senior Design I",
  "Senior Design II",
  "Tissue Engineering",
  "Surgical Technologies",
  "Bioengineering Professionalism",
  "Analytical Methods in Bioeng",
  "Computational Bioengineering",
  "Introduction to Biophysics",
  "Principles Bus Comm",
  "Prof Responsibility & Business",
  "Coaching for Success",
  "Business Dynamics",
  "Business in Action",
  "Project-Based Intro to CEE",
  "Systems Engrg & Economics",
  "Engineering Risk & Uncertainty",
  "Behavior of Materials",
  "Transportation Engineering",
  "Construction Engineering",
  "Environmental Engineering",
  "Energy and Global Environment",
  "Water Resources Engineering",
  "Structural Engineering",
  "Geotechnical Engineering",
  "Concrete Materials",
  "Pavement Design I",
  "High-Speed Rail Engineering",
  "Construction Planning",
  "Construction Cost Analysis",
  "Environmental Systems I",
  "Water Quality Engineering",
  "Env Eng Principles, Physical",
  "Steel Structures I",
  "Reinforced Concrete II",
  "Structural Analysis",
  "Structural Mechanics",
  "Structural Dynamics I",
  "Decision and Risk Analysis",
  "Sustainable Design Eng Tech",
  "Constr Equipment and Methods",
  "Data Science for CEE",
  "Theory & Creation of Structure",
  "Pavement Evaluation and Rehab",
  "Construction Case Studies",
  "Geotechnical Field Measurement",
  "Hidden World of Engineering",
  "Principles of CHE",
  "Thermodynamics",
  "Momentum and Heat Transfer",
  "Mass Transfer Operations",
  "Chemical Reaction Engineering",
  "Unit Operations Laboratory",
  "Process Design",
  "Process Control and Dynamics",
  "Bioenergy Technology",
  "Comp Methods in Chemical Engr",
  "Statistics in Chemical Engrg",
  "Assembly of Functional Materia",
  "Applied Mathematics in CHBE",
  "Stat Thermo Chem Eng",
  "Chemical Kinetics & Catalysis",
  "Introductory Chemistry",
  "General Chemistry I",
  "General Chemistry Lab I",
  "General Chemistry II",
  "General Chemistry Lab II",
  "Accelerated Chemistry I",
  "Accelerated Chemistry Lab I",
  "Quantitative Analysis Lecture",
  "Quantitative Analysis Lab",
  "Elementary Organic Chemistry I",
  "Elementary Organic Chem Lab I",
  "Fundamental Organic Chem I",
  "Structure and Synthesis",
  "Inorganic Chemistry",
  "Instrumental Chem Systems Lab",
  "Elementary Organic Chem II",
  "Instrumental Characterization",
  "Physical Chemistry Principles",
  "Physical Chemistry I",
  "Advanced Inorganic Chemistry",
  "Physical Organic Chemistry",
  "Advanced Organic Synthesis",
  "Concepts in Chemical Biology",
  "Introduction to Materials Chem",
  "Fourth-Year Chinese I",
  "Contemporary Health",
  "Introduction to Public Health",
  "Orientation KIN & Comm Health",
  "Mental Health",
  "Public Health Research Methods",
  "Human Sexuality",
  "Community Health Organizations",
  "Drug Use and Abuse",
  "Health Statistics",
  "Health Care Systems",
  "Introduction to Medical Ethics",
  "Introduction to Epidemiology",
  "Foundations of Health Behavior",
  "Orientation to Internship",
  "Gerontology",
  "Public Health Practice",
  "International Health",
  "Health Data Analysis",
  "Health Services Financing",
  "Organization of Health Care",
  "Health Planning",
  "Health Administration",
  "Counseling Techniques",
  "Health Behavior: Theory",
  "Principles of Epidemiology",
  "Health Economics",
  "Honors Uncommon Reads",
  "Intro to Digital Learning Env",
  "Tchg Diverse Middle Grade Stu",
  "Tchg Diverse High School Stu",
  "Intro Tchg Elem Age Children",
  "Thry Prac in Elem Schl Tch I",
  "Middle Schl Inst, Phil, & Str",
  "Lang Varieties,Cult,& Learning",
  "Families, Communities, Schools",
  "Teaching Children Mathematics",
  "Found of Bilingual Educ",
  "Tech Applications for Teachers",
  "Culture in the Classroom",
  "Tchg Elem Science I",
  "Lang Literacy in EC Educ I",
  "Princ Tchg Lit to Child Youth",
  "Teach Elem & Mid Lang Arts",
  "Intro to CS for CS Teachers",
  "Curr Dev for the 21st Century",
  "Linguistics for Classrm Teach",
  "Vocab Building-GRK & LAT Roots",
  "Medical Terms-GRK & LAT Roots",
  "Introduction to Greek Culture",
  "Mythology of Greece and Rome",
  "Storytelling & Transformation",
  "Archaeology of Israel",
  "Ancient Greek & Roman Religion",
  "Nightmares of Nero",
  "Amer Race&Ethnicity ClasicTrad",
  "Development of Ancient Cities",
  "Introduction to Communication",
  "Public Comm in Everyday Life",
  "Intro to Organizational Comm",
  "Small Group Communication",
  "Org Comm & Diversity",
  "Communicating Public Policy",
  "Intro to Interpersonal Comm",
  "Communication and Conflict",
  "Intro to Intercultural Comm",
  "Social Movement Communication",
  "Intro to Health Communication",
  "Intro to Mediated Comm",
  "Comm Technology & Society",
  "Strategies of Persuasion",
  "Family Communication",
  "Visual Politics",
  "Storytelling as Oral Comm",
  "Sexual Communication",
  "Digital Humanitarians",
  "Communication & Public Opinion",
  "Race & Digital Studies",
  "Applied Org Comm",
  "Social Media & Politics",
  "Risk Communication",
  "Photography & Public Life",
  "Workplace Comm Technology",
  "Adv Small Group Communication",
  "Persuasion Theory & Research",
  "Gender Communication",
  "Interpersonal Health Comm",
  "Social Marketing",
  "Foundational Skills in CropSci",
  "Introduction to Crop Sciences",
  "Agriculture in Mythology",
  "Applied Entomology",
  "Forage Crops & Pasture Ecology",
  "Applied Statistical Methods I",
  "Cannabis Classification & Mgmt",
  "Crop Sci Professional Develpmt",
  "Regression Analysis",
  "Freshman Orientation",
  "Intro Computing: Engrg & Sci",
  "Intro Computing: Non-Tech",
  "Intro to Computer Science I",
  "Intro to Computer Science II",
  "Discrete Structures",
  "CS 124 Freshman Honors",
  "CA Training",
  "Ethical & Professional Issues",
  "Data Structures",
  "Computer Architecture",
  "Intro to Computer Systems",
  "System Programming",
  "Programming Studio",
  "Numerical Methods I",
  "Prob & Stat for Computer Sci",
  "Intro to Algs & Models of Comp",
  "Text Information Systems",
  "Database Systems",
  "Introduction to Data Mining",
  "Interactive Computer Graphics",
  "Progrmg Languages & Compilers",
  "Real-Time Systems",
  "Distributed Systems",
  "Software Engineering I",
  "Computer System Organization",
  "Cloud Networking",
  "Topics in Internet of Things",
  "Communication Networks",
  "Artificial Intelligence",
  "Applied Machine Learning",
  "Computational Photography",
  "Machine Learning",
  "Natural Language Processing",
  "Numerical Analysis",
  "Computer Security I",
  "Computer Security II",
  "User Interface Design",
  "Introduction to Bioinformatics",
  "Algorithms",
  "Formal Software Devel Methods",
  "AI Applications in Education",
  "Mobile Robotics for CS",
  "Game Development",
  "Law &Policy Issues in CS",
  "The Art of Web Programming",
  "Advanced Data Management",
  "Scientific Visualization",
  "Topics in Software Engineering",
  "Deep Learning Theory",
  "Stat Reinforcement Learning",
  "Machine Learning for Signals",
  "Adv Topics in NLP",
  "Parallel Numerical Algorithms",
  "Adv Topics in Sec, Priv and ML",
  "Advanced Computer Security",
  "Social Spaces",
  "Computational Complexity",
  "Approximation Algorithms",
  "Foundations of Data Curation",
  "Transfer Learning",
  "Practical Statistical Learning",
  "Intro to Creative Writing",
  "Global Consciousness and Lit",
  "Lit of the Islamic World",
  "The Arab-Israeli Conflict",
  "Early Masterpieces West Cultur",
  "Responses to the Holocaust",
  "Intro to Contemporary Dance",
  "Modern Dance I",
  "Jazz Dance I",
  "Ballet I",
  "Explore Music through Dance",
  "Lyric Theatre Dance",
  "Design for Social Impact",
  "Pop Cultures Contemp East Asia",
  "Intro to Japanese Culture",
  "Masterpieces of East Asian Lit",
  "Introduction to Electronics",
  "Introduction to Computing",
  "Electrical & Electronic Ckts",
  "Electrical & Electronics Lab",
  "Analog Signal Processing",
  "Computer Systems & Programming",
  "Special Topics",
  "Digital Signal Processing",
  "Digital Signal Processing Lab",
  "Probability with Engrg Applic",
  "Ethics and Engineering",
  "Fields and Waves I",
  "Power Ckts & Electromechanics",
  "Green Electric Energy",
  "Semiconductor Electronics",
  "Electronic Circuits",
  "Data Science and Engineering",
  "Biomedical Imaging",
  "Digital Systems Laboratory",
  "Computer Systems Engineering",
  "Progm Mthds - Machine Learning",
  "Electronic Music Synthesis",
  "Cryptography",
  "Applied Parallel Programming",
  "Computer Organization & Design",
  "Multimedia Signal Processing",
  "IC Device Theory & Fabrication",
  "Senior Design Project Lab",
  "Wireless Communication Systems",
  "Power Electronics",
  "Power Electronics Laboratory",
  "Introduction to Robotics",
  "Power System Analysis",
  "Digital IC Design",
  "Control Systems",
  "Introduction to Optimization",
  "Control System Theory & Design",
  "EM Waves & Radiating Systems",
  "System-On-Chip Design",
  "Random Processes",
  "Pattern Recognition",
  "Computer Vision",
  "Optimiz by Vector Space Methds",
  "Microeconomic Principles",
  "Macroeconomic Principles",
  "Economic Statistics I",
  "Economic Statistics II",
  "Inter Microeconomic Theory",
  "Inter Macroeconomic Theory",
  "International Economics",
  "Macroeconomic Policy",
  "Monetary Economics and Policy",
  "Game Theory",
  "Economics of Labor Markets",
  "Development Economics",
  "Intro to Applied Econometrics",
  "Financial Econometrics",
  "Econometrics of Policy Eval",
  "Economic Forecasting",
  "Industrial Comp and Monopoly",
  "Economics of Digital Economy",
  "Law and Economics",
  "Consumer & Investor Protection",
  "Economic Developmt & Migration",
  "Int'l Environmental Policy",
  "Predictive Analytics",
  "Women in the Economy",
  "Microeconomics",
  "Macroeconomics",
  "Economic Statistics",
  "Introduction to Game Theory",
  "Economics of Taxation",
  "Monetary Theory",
  "Microeconomics for Business",
  "Econometric Analysis I",
  "Adv Student Research Seminar",
  "Applied Econometrics for Micro",
  "Education Orientation Seminar",
  "Mentoring in Education: Mentee",
  "Identity and Difference in Edu",
  "Social Justice Sch & Society",
  "Engl Grammar for ESL Teachers",
  "Engineering at Illinois",
  "Introduction to Sustainability",
  "GFX Leadership Scholars",
  "GFX-POETS Project Scholars",
  "Spatial Visualization",
  "GFX Global Sustainability Scho",
  "Technical Communication",
  "Intro to Engrg-ARISE",
  "Undergraduate Research Seminar",
  "MEP Mentoring",
  "Road Map to Grad School",
  "Success and Wellness",
  "Engrg Transfer Orientation",
  "Grainger Engr: Design Your Exc",
  "Seminar Energy & Sustain Engrg",
  "Cubesat 1",
  "Teaching and Leadership",
  "Intro to Poetry",
  "Intro to Fiction",
  "Introduction to Film",
  "Intro to Fiction-ACP",
  "Intro to American Literature",
  "Literature of Fantasy",
  "Introduction to Comics",
  "Intro to Lit and Culture",
  "Medieval Lit and Culture",
  "Renaissance Lit and Culture",
  "Enlightenment Lit and Culture",
  "Romantic Lit and Culture",
  "Modernist Lit and Culture",
  "Legends of King Arthur",
  "Introduction to Shakespeare",
  "Early African American Lit",
  "Modern African American Lit",
  "American Cinema, 1950-2000",
  "Postcolonial Lit in English",
  "Topics in LGBT Lit and Film",
  "Writing Lit, Text & Culture",
  "Disability and Film",
  "Topics In Writing Studies",
  "Air Pollution to Global Change",
  "Asian American Education",
  "Professional Ethics in Educ",
  "Critical Thinking in Education",
  "Racial and Ethnic Families",
  "Principles of HRE",
  "Instruct & Train System Design",
  "Work Analysis",
  "Learning Technologies",
  "Proseminar in EPOL",
  "Race, Gender & Sexuality Issu",
  "Education and Human Rights",
  "Diversity, Leadership & Policy",
  "Management of HRD",
  "Learning on the Job",
  "Program Evaluation",
  "Globalizing Educational Policy",
  "Educational Psychology",
  "Exploring Cultural Diversity",
  "Career Theory and Practice",
  "Child Language and Education",
  "Theories of Psychotherapy",
  "Early Adolescent Development",
  "Human Perform & Cogn in Contxt",
  "Educational Statistics",
  "Assessing Student Performance",
  "Qualitative Inquiry Methods",
  "Statistical Inference in Educ",
  "Earth Systems",
  "Water Planet, Water Crisis",
  "Arts at Illinois",
  "Design Beyond Boundaries",
  "Sustainable Design Built Envir",
  "Corporate Finance",
  "Introduction to Insurance",
  "Fundamentals of Real Estate",
  "Financial Markets",
  "Advanced Corporate Finance",
  "Finance Academy",
  "Investment & Portfolio Mngt",
  "Options and Futures Markets",
  "Financial Modeling",
  "Financing Emerging Businesses",
  "Mergers and Acquisition",
  "Employee Benefit Plans",
  "Personal Wealth Management",
  "Real Estate Investment",
  "Investment Banking",
  "Introduction to Finance",
  "Econ of Market Fundamentals",
  "Quantitative Finance",
  "Quantitative Finance II",
  "Big Data Analytics in Finance",
  "Investments",
  "Financial Derivatives",
  "Machine Learning in Finance",
  "Algorithmic Mkt Microstructure",
  "Option Trading & Market-Making",
  "Data Science & Python for Fin.",
  "Adv. Data Sci & Python for Fin",
  "Exploring Paris",
  "Language&Minorities in Europe",
  "The Science of Food",
  "Contemporary Nutrition",
  "Introduction to Hospitality",
  "Introduction to Dietetics",
  "Science of Fermented Foods",
  "Hot Topics in Sports Nutrition",
  "Principles of Nutrition",
  "Science of Food Preparation",
  "Food Service Sanitation",
  "Sensory Evaluation of Foods",
  "Foundations in Beverage Mgmt",
  "Strategic Operations Mgmt",
  "Food Chemistry",
  "Food Chemistry Laboratory",
  "Food Ingredient Technology",
  "Nutritional Aspects of Disease",
  "Intro Personalized Nutrition",
  "Biochemical Nutrition I",
  "Food Processing Engineering",
  "Food Processing Unit Ops II",
  "Advanced Food Chemistry",
  "Global Development&Environment",
  "The Digital Earth",
  "Geographies of Globalization",
  "Social & Environmental Issues",
  "Geographies of Global Conflict",
  "Intro to GIS Systems",
  "CyberGIS & Geospatial Data Sci",
  "Introduction to Remote Sensing",
  "High-Perf Geospatial Computing",
  "Physical Geology",
  "The Oceans",
  "Natural Disasters",
  "History of Life",
  "Intermediate German I",
  "Grimm's Fairy Tales in Context",
  "History of Sexuality",
  "Intro to Global Studies",
  "Career Development:Internships",
  "Global Health",
  "Poverty in a Global Context",
  "Exploring General Studies",
  "DGS Honors Seminar",
  "Intro Gender & Women's Studies",
  "Race, Gender & Power",
  "Queer Lives, Queer Politics",
  "The Politics of Fashion",
  "Digital & Gender Cultures",
  "Queer Theory",
  "Black Women & Popular Culture",
  "Transnational Sexualities",
  "Opportunities, Careers in HDFS",
  "Intro to Human Development",
  "Grief/Loss Across the Lifespan",
  "Intro to Family Studies",
  "Child Fam with Special Needs",
  "Families in Global Perspective",
  "Close Relationships",
  "Intro to Research Methods",
  "Infancy & Early Childhood",
  "Adult Development",
  "Families and the Law",
  "Socialization and Development",
  "Adolescent Development",
  "Family Stress and Change",
  "Global History",
  "History of Everything",
  "Black Music",
  "History of Africa to 1800",
  "East Asian Civilizations",
  "History of South Asia",
  "US History to 1877",
  "US History Since 1877",
  "Reacting to the Past",
  "Lived Experience Latin America",
  "Digital Documentary Publishing",
  "Traditional China",
  "Wives, Workers and Witches",
  "20thC World to Midcentury",
  "Zionism: A Global History",
  "Illinois History",
  "Encounters in Native America",
  "Constructing Race in America",
  "US Gender History to 1877",
  "History of Mexico from 1519",
  "The Caribbean Since 1492",
  "Immigrant America",
  "Twentieth Century Europe",
  "Fict & Historical Imagination",
  "America's Republic, 1780-1880",
  "Integration & American Sports",
  "The 1960s in the U.S.",
  "Hidden Political Figures",
  "Twentieth-Century Japan",
  "Roman Republic to 44 B C",
  "Vegetable Gardening",
  "The Sustainable Home Garden",
  "Biology in Today's World",
  "Animal Biology",
  "The Biology of Dinosaurs",
  "Race and Environmental Biology",
  "Organismal & Evolutionary Biol",
  "Ecology",
  "Genetics",
  "Pandemics",
  "Anatomy",
  "Evolution and Human Health",
  "Marine Biology",
  "Ecology and Evolution",
  "Bioinspiration",
  "Mammalogy",
  "Insect Classification and Evol",
  "Insect Pest Management",
  "Analysis of Biological Data in",
  "Analysis of Data",
  "Determin Models in Optmzation",
  "Design & Anlys of Experiments",
  "Computing for ISE",
  "Optimization of Large Systems",
  "Design for Six Sigma",
  "Deep Learning Math & Appl",
  "Statistical Methods in Finance",
  "Financial Computing",
  "Optimization in Finance",
  "Stats of Big Data & Clustering",
  "Introduction to i-Health",
  "Survey of Interdisc Health",
  "Leadership in Health",
  "Aging and Health Policy",
  "Interdis Collab in Health Serv",
  "Pre-Field Experience in Health",
  "Intro to Video Game Industry",
  "Intro to Prog for Data Science",
  "Data Machines and the Python",
  "Exploring the iSchool",
  "Intro to Information Sciences",
  "iSchool Explore, Engage, Devel",
  "Social Hist of Games & Gaming",
  "Social Aspects Info Tech",
  "Analytical Fndts Info Problems",
  "Research Design Info Sciences",
  "Program for Info Problems",
  "Intro Database Concepts & Apps",
  "Introduction to HCI",
  "Web Design Fundamentals",
  "Program for Info Problems II",
  "Race, Gender, and Info Tech",
  "Computers and Culture",
  "History Fndts of Info Society",
  "Consulting Info Professionals",
  "Introduction to Data Science",
  "Early Literacy",
  "Foundations Info Processing",
  "Data Visualization",
  "Systems Analysis and Design",
  "Database Design & Prototyping",
  "Instruc Strat Tech Info Prof",
  "Design for Social Interact Exp",
  "Reference and Info Services",
  "Info Org and Access",
  "Data, Stat, Info",
  "Libraries Info and Society",
  "Information Modeling",
  "Research Design in IS",
  "Preserving Info Resources",
  "Data Warehousing and BI",
  "Collection Development",
  "Youth Services Librarianship",
  "Fantasy Lit/Media for Youth",
  "Info Service for Diverse Users",
  "Data Mining",
  "Academic Librarianship",
  "Rare Books and Special Collect",
  "Bookbinding: Hist, Princ, Prac",
  "E-Learning",
  "AV Materials Libs & Archives",
  "Progr Analytics & Data Process",
  "Responsible Data Science & AI",
  "Exploring Rome",
  "Interactive Media & You",
  "Introduction to Journalism",
  "History of American Journalism",
  "Journalism Ethics & Diversity",
  "Digital Photography 4 Everyone",
  "Media Law",
  "Adv Public Affairs Reporting",
  "Classics of Sports Journalism",
  "Media and Public Opinion",
  "Crisis Communications",
  "Cond & Wt Control",
  "Walking and Movement Wellness",
  "Bowling",
  "Badminton",
  "Ice Skating",
  "Aqua Aerobics",
  "Volleyball",
  "Physical Activity and Health",
  "Social Sci of Human Movement",
  "Contemporary Issues in Sport",
  "Bioscience of Human Movement",
  "Introduction to Kinesiology",
  "Medical Terminology",
  "Stress Management",
  "Phys Activity Research Methods",
  "Intro to Sport Psychology",
  "Sport & Modern Society",
  "Motor Development and Control",
  "Motor Develop, Growth & Form",
  "Children's Movement",
  "Soc & Psych of Phys Activity",
  "Bioenergetics of Movement",
  "Biomechanics of Human Movement",
  "Coaching Strategies",
  "Measure & Eval in Kinesiology",
  "Phys Act & Chronic Disease",
  "Exercise & Health Psychology",
  "Nutrition for Performance",
  "Elementary Korean I",
  "Introduction to Landscape Arch",
  "Foundation Design Studio",
  "Landform Design & Construction",
  "Design Communications I",
  "Site Engineering",
  "Professional Practice",
  "Woody Landscape Plants",
  "Regional Design Studio",
  "Natural Precedent in Planting",
  "Success in LAS - IntlStudents",
  "Design First Year Experience",
  "Social Innov for Global Chllgs",
  "Global Perspectives-Pre-Depart",
  "Leadership & Prof Development",
  "Introduction to Latin America",
  "Introduction to Law",
  "Professional Resp Crim (Grad)",
  "Professional Resp (GRAD)",
  "Contracts",
  "Property",
  "Torts",
  "Criminal Law",
  "Criminal Proc: Investigation",
  "Civil Procedure",
  "Legal Writing & Analysis",
  "Legal Research",
  "Bankruptcy",
  "Business Associations I",
  "Business Associations - Grad",
  "Copyright Law",
  "Patent Law",
  "Income Taxation",
  "International Law",
  "Labor Law I",
  "Family Law",
  "Professional Responsibility",
  "Evidence",
  "Federal Courts",
  "Trial Advocacy",
  "Animal Law",
  "Real Estate Transactions",
  "Doing Business in Japan",
  "Counter-Terrorism Law & Policy",
  "Intro to Intellectual Property",
  "Interpersonal Intelligence",
  "Leadership Communications",
  "Foundations of Leadership",
  "Leadership Ethics & Society",
  "Leadership in Groups and Teams",
  "Collaborative Leadership",
  "Introduction to Labor Studies",
  "Org Fundamentals for HR",
  "Compensation Systems",
  "HR Planning and Staffing",
  "HR Training and Development",
  "HR Management and Strategy",
  "International HR Management",
  "Power & Influence in HRM",
  "Compar Employ Relations System",
  "Executive Compensation",
  "Economics Gender & Workforce",
  "Empl. stress, well-being & saf",
  "Game Theory & Strategy",
  "Leadership & Employ Engagement",
  "Social Networks in HRM",
  "Employment Relations Systems",
  "Quantitative Methods in LER",
  "Managing Diversity Globally",
  "Intro to Language Science",
  "Language and Culture in India",
  "Language History",
  "Language in Globalization",
  "Language, Mind, and Brain",
  "Linguistic Diversity in the US",
  "Language, Technology & Society",
  "Elements of Syntax",
  "Elmnts Semantics & Pragmatics",
  "Intro to General Phonetics",
  "Corpus Linguistics",
  "Sociolinguistics I",
  "Intro Latina/Latino Studies",
  "Latina/o Migration",
  "Latina/o Genders & Sexualities",
  "Race, Politics, & Reproduction",
  "Latina/o Popular Culture",
  "Intro to Latina/o Literature",
  "Latina/os on the Bronze Screen",
  "Mexican-American History",
  "Literatures of the Displaced",
  "Race, Gender and the Body",
  "Intro to Popular TV & Movies",
  "Intro to the Media",
  "Smartphone Cinema",
  "Intro Digital Media Production",
  "Contemporary Media Literacy",
  "Contemporary Movies",
  "Film Production",
  "Survey of World Cinema I",
  "Creative and Info Economies",
  "Horror Movie",
  "Media History",
  "Popular Culture",
  "New Media, Culture & Society",
  "Social Aspects of Media",
  "Sex & Gender in Popular Media",
  "PR & Entertainment Industry",
  "Documentary & Music Culture",
  "Thinking Mathematically",
  "Theory of Arithmetic",
  "Algebra",
  "Preparation for Calculus",
  "Finite Mathematics",
  "Elementary Linear Algebra",
  "A Mathematical World",
  "Basic Discrete Mathematics",
  "Calculus",
  "Calculus I",
  "Introductory Matrix Theory",
  "Calculus II",
  "Calculus III",
  "Linear Algebra w Computat Appl",
  "Intro Differential Equations",
  "Intro to Differential Eq Plus",
  "Topics in Mathematics",
  "Fundamental Mathematics",
  "Teacher's Course",
  "Graph Theory",
  "Intro to Combinatorics",
  "Applied Linear Algebra",
  "Abstract Linear Algebra",
  "Honors Real Analysis",
  "Honors Abstract Algebra",
  "Differential Equations",
  "Elementary Real Analysis",
  "Applied Complex Variables",
  "Real Variables",
  "Number Theory",
  "Linear Programming",
  "Abstract Algebra I",
  "Real Analysis",
  "Complex Variables I",
  "Digital Media & Marketing",
  "Marketing in an Analog World",
  "Global Impact:CulPsych&BusEth",
  "Entrep: From Startup to Growth",
  "Applying Data Analytics Mrktg",
  "Applying Data Analytics inACCY",
  "Introductory Microbiology",
  "Intro Microbiology Laboratory",
  "Molec & Cellular Basis of Life",
  "Molec & Cellular Laboratory",
  "Society and the Brain",
  "Human Anatomy & Physiology I",
  "Human Anat & Physiol Lab I",
  "Exp Techniqs in Molecular Biol",
  "Cells, Tissues & Development",
  "Exp Techniqs in Cellular Biol",
  "Microbiology",
  "Experimental Microbiology",
  "Introduction to Neurobiology",
  "Biochem & Phys Basis of Life",
  "Cancer Cell Biology",
  "Cellular Physiology",
  "Immunology",
  "Endocrinology",
  "Microbial Pathogens Laboratory",
  "Global Biosecurity",
  "Introductory Biochemistry",
  "Cell & Molecular Neuroscience",
  "Special Topics Mol Cell Biol",
  "Virology",
  "Advanced Biochemistry",
  "Advanced Molec & Cell Biology",
  "Scientific Writing",
  "College of Media Orientation",
  "Computer-Aided Design",
  "Automotive Design Projects-DES",
  "Automotive Design Projects-SAE",
  "Design for Manufacturability",
  "Fundamentals of Fluid Dynamics",
  "Heat Transfer",
  "Engineering Materials",
  "Dynamics of Mechanical Systems",
  "Signal Processing",
  "Mechanical Design I",
  "Mechanical Design II",
  "Intermediate Heat Transfer",
  "Failure of Engrg Materials",
  "Fundamentals of Photovoltaics",
  "Comp Design & Dyn of Soft Syst",
  "Computer-Aided Mfg Systems",
  "Computer Cntrl of Mech Systems",
  "Advanced Computer Control",
  "Senior Design Project",
  "Finite Element Analysis",
  "Bioinspired Design",
  "MEMS-NEMS Theory & Fabrication",
  "Intro to US Armed Forces",
  "Materials in Today's World",
  "Introduction to MatSE",
  "Phases and Phase Relations",
  "Materials Laboratory I",
  "Introduction to Research",
  "Thermodynamics of Materials",
  "Synthesis of Materials",
  "Thermal-Mech Behavior of Matls",
  "Design of Engineering Alloys",
  "Polymer Chemistry",
  "Electronic Materials II",
  "Design and Use of Biomaterials",
  "Surfaces and Colloids",
  "Atomic Scale Simulations",
  "Optical Materials",
  "Statistical Thermodyn of Matls",
  "Music Theory and Practice I",
  "Popular Music Studies",
  "Introduction to World Music",
  "Music Theory and Practice III",
  "Introductory Music Ed Tech",
  "The History of Music I",
  "Music in Adolescence",
  "Music Teaching in Ens Settings",
  "Elect Music Techniques I",
  "Viennese Classical 18th c",
  "Differentiating Music Instrctn",
  "Post Tonal Theory",
  "University Chorus",
  "Black Chorus",
  "Women's Glee Club",
  "Wind Symphony",
  "Marching Illini",
  "Introduction to Museums",
  "Orientation to NPRE",
  "Energy Systems",
  "Modeling Nuclear Energy System",
  "Nuclear Power Engineering",
  "Materials in Nuclear Engrg",
  "Radiation Interact w/Matter I",
  "Nuclear Syst Engrg & Design",
  "Safety Anlys Nucl Reactor Syst",
  "Writing on Technol & Security",
  "Fundamentals of Nuclear Engrg",
  "Fundamentals of Env Sci",
  "Introduction to NRES",
  "The Great Lakes at Risk",
  "Introductory Soils",
  "Applied Ecology",
  "Social Justice and Environment",
  "Fish and Wildlife Ecology",
  "Watershed Hydrology",
  "Fishery Ecol and Conservation",
  "Native Plant ID and Floristics",
  "Env and Plant Ecosystems",
  "Quantitative Methods in NRES",
  "GIS in Natural Resource Mgmt",
  "Landscape Ecology",
  "Pedology",
  "Introduction to Philosophy",
  "Logic and Reasoning",
  "Logic and Reasoning QR II",
  "Symbolic Logic",
  "Ancient Philosophy",
  "Early Modern Philosophy",
  "Biomedical Ethics",
  "Philosophical Foundations CS",
  "Philosophy of Science",
  "Nineteenth Century Philosophy",
  "Major Recent Philosophers",
  "Ethical Theories",
  "Thinking About Physics",
  "College Physics: Mech & Heat",
  "College Physics: E&M & Modern",
  "University Physics: Mechanics",
  "University Physics: Elec & Mag",
  "Univ Physics: Thermal Physics",
  "Univ Physics: Quantum Physics",
  "Relativity & Math Applications",
  "Classical Mechanics I",
  "Classical Mechanics II",
  "Classical Physics Lab",
  "Light",
  "Thermal & Statistical Physics",
  "Electromagnetic Fields I",
  "Electromagnetic Fields II",
  "Atomic Phys & Quantum Theory",
  "Quantum Physics I",
  "Quantum Physics II",
  "Mathematical Physics I",
  "Quantum Mechanics I",
  "Graduate Physics Orientation",
  "AdS/QFT Correspondence",
  "Plants, Pathogens, and People",
  "Intro to Political Science",
  "Intro to US Gov & Pol",
  "US Racial & Ethnic Politics",
  "American Indian Law & Politics",
  "Intro to Public Policy",
  "Politics of the National Parks",
  "Strategic Models",
  "Intro to Comp Politics",
  "Comp Politics in Dev Nations",
  "Intro to Political Theory",
  "Intro to Intl Relations",
  "Intro to Intl Relations-ACP",
  "Governing Globalization",
  "Terrorism",
  "The US Constitution I",
  "Political Psychology",
  "Public Opinion",
  "Principles of Public Policy",
  "Law and Representation",
  "Intro to Political Behavior",
  "Gov & Pol in Western Europe",
  "American Foreign Policy",
  "International Conflict",
  "Intro Psych",
  "Intro to Social Psych",
  "Intro to Brain and Cognition",
  "Psych of Prejudice & Discrim",
  "Behavioral Neuroscience",
  "Child Psych",
  "Cognitive Psych",
  "Perception & Sensory Processes",
  "Intro to Statistics",
  "Psychopathol & Probs in Living",
  "Community Psych",
  "Industrial Org Psych",
  "Learning and Memory",
  "Psych of Personality",
  "Psychology of Race & Ethnicity",
  "Drugs, Brain and Behavior",
  "Developmental Psychopathology",
  "Cognitive Psych Lab",
  "Social Psych in Society Lab",
  "Self In Virtual Communities",
  "Stress&Resilency in Childhood",
  "CounselCenterParaProfessional",
  "Mindfulness SrvceLearning Pt 1",
  "Personality Lab",
  "Social Cognition",
  "Developmental Child Psych Lab",
  "Decisions and Judgments",
  "Memory and Amnesia",
  "Human Behavior Genetics",
  "Neurosci of Eating & Drinking",
  "Principles of Psychophysiology",
  "Evolutionary Neuroscience",
  "Cog Neuroscience of Vision",
  "Personality and Soc Dev",
  "Psych and Law",
  "Personnel Psych",
  "Statistical Methods I",
  "Seminar in Cognitive Science",
  "Disability in American Society",
  "Medical Aspects of Disability",
  "Asian Mythology",
  "Religion & Society in West I",
  "World Religions",
  "Introduction to Islam",
  "Religion, Violence & America",
  "Adv Rhetoric & Composition",
  "RST in Modern Society",
  "RST In Modern Society",
  "Orientation to RST",
  "Student-Athlete Transition",
  "Park, Recreation & Environment",
  "Foundations of Sport Mgt",
  "Foundations of Tourism",
  "E-Sports Foundations",
  "Leadership in RST",
  "Sport and the Big Ten",
  "Management in RST",
  "Technology in RST",
  "Diversity in RST",
  "Nature and American Culture",
  "Ethical Issues in RST",
  "Disability in RST",
  "Human Development and RST",
  "Marketing in RST",
  "Facility Management in RST",
  "Legal Aspects of Sport",
  "Communication in RST",
  "Research Methods & Analysis",
  "Strategic Thinking in RST",
  "Contemporary Issues in RST",
  "Sport & Development",
  "Event Management in RST",
  "Event Implementation in RST",
  "SBC Essentials",
  "Strat Branding: Global Persp",
  "Essentials of Business Mgmt",
  "Consumer Insights I",
  "Messaging Strategy",
  "Strat. Analytics & Data Visual",
  "Professional SBC Capstone Proj",
  "Madness, Myth, and Murder",
  "Viking Mythology",
  "Introduction to ISE",
  "Business Side of Engineering",
  "Dsgn of Structures & Mechanism",
  "Emotional Intelligence Skills",
  "Engineering Law",
  "Component Design",
  "Digital Control Systems",
  "Decision Analysis I",
  "Senior Engineering Project I",
  "Senior Engineering Project II",
  "Child, Comm, & Lang Ability",
  "American Sign Language I",
  "Intro Hum Comm Sys & Disorders",
  "American Sign Language II",
  "Lang&Culture Deaf Communities",
  "Communication Neuroscience",
  "Anat & Physiol Spch Mechanism",
  "Development of Spoken Language",
  "American Sign Language III",
  "Child Neurodev Disorders",
  "Lang Disorders Preschool Child",
  "Intro Audiol & Hear Disorders",
  "Aural Rehab Children to Adults",
  "Neural Bases Spch Lang",
  "Asst & Mgmt of Voice Disorders",
  "Aphasia and Related Disorders",
  "Quant Reasoning Spch Hear Sci",
  "Advanced Practicum in SHS",
  "Russ & E Euro Science Fiction",
  "Introduction to Sociology",
  "Sociology of Gender",
  "Global Ineq and Social Change",
  "Social Problems",
  "America's Immigrant Society",
  "Career Dev for Sociology Major",
  "Intro to Sociological Theory",
  "Race and Ethnicity",
  "Political Sociology",
  "Criminology",
  "Intro to Social Statistics",
  "Sociology of Deviance",
  "Technology and Society",
  "Impacts of Globalization",
  "Sociology of Law",
  "Social Research Methods",
  "Health Communication in the US",
  "Law and Society",
  "SOCW Orientation Seminar",
  "Introduction to Social Work",
  "Social Work Statistics",
  "Death & Dying",
  "Asian Families in America",
  "Diversity: Identities & Issues",
  "Social Serv for Older Adults",
  "Social Work and the Military",
  "Practice I",
  "Practice III",
  "Social Welfare Pol and Svcs",
  "Child Welfare Issues & Trends",
  "Subst Use in Social Context",
  "Social Work Research Methods",
  "HBSE I: Human Development",
  "Social Work with Women",
  "Trauma Informed SW w/ Children",
  "Adv Clin Assess & Interviewing",
  "HBSE II: Mental Disorders",
  "Cognitive Behavioral Therapy",
  "Social Work and the Law",
  "Spanish in the Community",
  "Latin American Diaspora Film",
  "Spanish in the United States",
  "The Culture of Disability",
  "Gen Educator's Role in SPED",
  "Instructional Strategies I",
  "Curriculum Development I",
  "Introduction to ECSE",
  "AAC and Literacy",
  "Learning Environments I",
  "Learning Environments II",
  "Equity Issues in Spec Educ",
  "Statistics",
  "Data Science Discovery",
  "Statistical Analysis",
  "Data Science Exploration",
  "Biostatistics",
  "Statistics Programming Methods",
  "Statistics and Probability I",
  "Actuarial Statistics II",
  "Statistics and Probability II",
  "Methods of Applied Statistics",
  "Statistical Modeling I",
  "Statistical Modeling II",
  "Statistical Computing",
  "Time Series Analysis",
  "Python in Data Science Program",
  "Fundamentals of Deep Learning",
  "Unsupervised Learning",
  "Applied Bayesian Analysis",
  "Basics of Statistical Learning",
  "Statistical Data Management",
  "Professional Statistics",
  "Data Science Prog Methods",
  "Mathematical Statistics",
  "Advanced Regression Analysis",
  "Statistical Learning",
  "Multivariate Analysis",
  "Mechanics in the Modern World",
  "Mechanics for Technol & Mgmt",
  "Introduction to Statics",
  "Statics",
  "Introductory Dynamics",
  "Introductory Solid Mechanics",
  "Introductory Fluid Mechanics",
  "Cellular Biomechanics",
  "Computational Mechanics",
  "Mathematical Methods I",
  "Solid Mechanics I",
  "Introduction to Innovation",
  "From Idea to Enterprise",
  "Creativity, Innovation, Vision",
  "Lect in Engrg Entrepreneurship",
  "Startups:Inc,Fund,Contracts,IP",
  "Technol Innovation & Strategy",
  "Practicum I",
  "Introduction to Theatre Arts",
  "Broadway Musicals",
  "Foundations: Performance",
  "Foundations: Production",
  "Intro African American Theat",
  "Relationships in Acting I",
  "History of Theatre I",
  "Creative Project",
  "Technical Systems in Agr",
  "Agric Machinery Technology",
  "Basics of CAD",
  "Materials and Construction Sys",
  "Metallurgy & Welding Process",
  "Humanity in the Food Web",
  "Land and Water Mgt Systems",
  "Environ Control & HVAC Systems",
  "Introduction to City Planning",
  "Race, Social Justice, Cities",
  "Cities: Planning & Urban Life",
  "Social Inequality and Planning",
  "Communication for Planners",
  "GIS for Planners",
  "Planning with Climate Change",
  "Neighborhood Analysis",
  "Physical Planning",
  "Urban History and Theory",
  "Livestock Biostatistics",
  "Food Supply Disease Prevention",
  "Structure and Function I",
  "Pathobiology I",
  "Pathobiology II",
  "SA Medicine and Surgery I",
  "LA Medicine and Surgery I",
  "SA Medicine and Surgery II",
  "LA Medicine and Surgery II",
  "US Citizenship Comparatively",
  "Asian American Youth in Film",
  "Muslims in America",
  "ABE Principles: Bioenvironment",
  "ABE Principles: Bioprocessing",
  "Engrg Measurement Systems",
  "NPS Pollution Processes",
  "Industry-Linked Design Project",
  "Accounting Analysis I",
  "Accounting Analysis II-B",
  "Managerial Accounting A",
  "Managerial Accounting B",
  "Taxation of Bus Entities A",
  "Taxation of Bus Entities B",
  "Data Analytics for Mgmt Acctg",
  "Partnership Income Taxation",
  "Stat Analyses for Accountancy",
  "Risk Management and Innovation",
  "Data Analytics Apps in ACCY",
  "Data Preparation for Accting",
  "Machine Learning for Accting",
  "Food and Agribusiness Mgt",
  "Farm Management",
  "Economic Systems in Africa",
  "Econ of Food & Enviro Justice",
  "Consumer Economics",
  "Food Law",
  "Food Marketing and Behavior",
  "Issues&Careers in Applied Econ",
  "Spreadsheet Models & Applic",
  "Financial Planning Technologie",
  "Energy Economics",
  "Food Marketing",
  "Agri-food Strategic Management",
  "Finan Plan for Professionals",
  "Modeling App's Finan Plan",
  "Retirement & Benefit Planning",
  "Agriculture in Intl Dev",
  "Agr and Food Policies",
  "Data Science for Applied Econo",
  "Intro Sustainable Food Systems",
  "Sports PR",
  "Writing for Public Relations",
  "NSAC Campaign",
  "Public Relations Strategies",
  "Social Media Analytics",
  "Compressible Flow",
  "Aerospace Numerical Methods",
  "Computational Aerodynamics",
  "Electric Propulsion",
  "Aerospace Systems Design II",
  "Structures & Control Lab",
  "Intro to Human Spaceflight",
  "Advanced Orbital Mechanics",
  "Black Women in the Diaspora",
  "Black Literature in America",
  "Race and Food Security",
  "Hip Hop Music: History&Culture",
  "Intro to the African Diaspora",
  "Intro to Mod African Lit",
  "Ag & Env Photography",
  "Public Information Campaigns",
  "Indigenous Thinkers",
  "Volunteer Management",
  "Contemporary Animal Issues",
  "Animal Nutrition",
  "Animal Reproduction and Growth",
  "Behavior of Domestic Animals",
  "Companion Animal Policy",
  "Zoo Animal Conservation Sci",
  "Animal Shelter Management",
  "Meat Science",
  "Lactation Biology",
  "Population Genetics",
  "Comparative Immunobiology",
  "Protein and Energy Nutrition",
  "Adv Companion Animal Nutrition",
  "Latin American Cultures",
  "Sociocultural Anthropology",
  "Evolution and Human Disease",
  "Images of the Other",
  "Museum Theory and Practice",
  "Drawing and Modeling",
  "Structural Fundamentals",
  "Representation",
  "Rome: City of Visible History",
  "Architecture of the U.S.",
  "Struct Sys and Const Methods",
  "Architectural Practice",
  "Arch History 1850-Present",
  "Design & Construction Futures",
  "Design Thinking",
  "Interaction Design Foundation",
  "Exploring Anime",
  "Queer Manga",
  "Illustration",
  "Sustainability & Manufacturing",
  "Advanced Interaction Design",
  "Professional Design Practice",
  "Graphic Design Capstone",
  "Art, Design, and Society",
  "Design History Survey",
  "Art and Power in 17th c Europe",
  "Art Since 1940",
  "Contemporary Art",
  "Word and Image in Chinese Art",
  "Stoch Proc for Fin & Insurance",
  "Life Contingencies II",
  "Computing in Astronomy",
  "Extraterrestrial Life",
  "Planetary Systems",
  "Astronomical Techniques",
  "Cloud Physics",
  "Data Science for Geosciences",
  "Leading Individuals and Teams",
  "Designing and Managing Orgs",
  "Marketing to Business and Govt",
  "Brand Management",
  "E-Business Management",
  "Bus Prob Form and Soln",
  "Product Design and Development",
  "Business Process Improvement",
  "International Marketing",
  "Corporate & Commercial Law",
  "Advanced Marketing Management",
  "Global Business",
  "Technology Strategy",
  "Strategic Management",
  "Digital Business & IT Strategy",
  "Decision Analytics",
  "Predictive Data Analytics",
  "Global Marketing",
  "Consumer Analytics",
  "Frontiers in Management",
  "Entrepreneurship",
  "Product Design & Development",
  "Operations Analysis",
  "Intro to DA Apps in Bus",
  "Physical Biochemistry",
  "Technqs Biochem & Biotech",
  "Biomedical Data Analysis",
  "Signals & Systems in Bioengrg",
  "Linear Alg for Biomed Data Sci",
  "Comp Tools Bio Data",
  "Transport & Flow in Bioengrg",
  "Intro Bio Control Systems",
  "Quant Pharmacology",
  "Persuasive Writing",
  "Global Business Perspectives",
  "Construction Productivity",
  "Environmental Engineering Lab",
  "Reinforced Concrete I",
  "Steel Structures II",
  "Applied Soil Mechanics",
  "Construction Safety",
  "Construction Data Modeling",
  "Water Quality Control Proc I",
  "Finite Element Methods",
  "Earthquake Engineering",
  "Electrochemical Engineering",
  "Biochemical Engineering",
  "Heat and Mass Transfer",
  "Bioinformatics",
  "Chemistry, Everyday Phenomena",
  "Accelerated Chemistry II",
  "Accelerated Chemistry Lab II",
  "Chemistry of the Environment",
  "Fundamental Organic Chem II",
  "Physical Chemistry II",
  "Drug Discovery & Development",
  "Electrochemical Methods",
  "Structure and Spectroscopy",
  "Physical Methods Mat Chem",
  "Disability, Culture & Society",
  "Women's Health",
  "Military Veterans",
  "Biostatistics in Public Health",
  "Special Topics: Uncommon Reads",
  "Intro Tchg in a Diverse Societ",
  "Tchg and Assessing Sec Sch Stu",
  "Thry Prac in Elem Schl Tchg II",
  "Tchg Elementary Mathematics",
  "Invest Approach Elem Math Inst",
  "Critiques of Educational Tech",
  "Tchg Elem Science II",
  "Disciplinary Literacy",
  "Teach Elem Rdg & Lang Arts I",
  "Biling ESL Methods & Material",
  "The Roman Achievement",
  "The Classical Tradition",
  "Animals in Literature",
  "Sports and Society Greece Rome",
  "The Comic Imagination",
  "Argumentation",
  "Rhetorical Performance Styles",
  "Visual Media Effects",
  "The American Family",
  "Rhetoric of Theatre",
  "Comm & Public Opinion",
  "Race, Class, Gender & Work",
  "Black Freedom Stuggle",
  "Adv Organizational Comm",
  "Campaigning to Win",
  "Adv Interpersonal Comm",
  "Comm in Personal Relationships",
  "Organizational Health Comm",
  "Provider Patient Communication",
  "Environment, Agric, & Society",
  "The Global Food Production Web",
  "Agric. & Science of Coffee",
  "Intro to Plant Protection",
  "Genetic Engineering Lab",
  "Crop Growth and Management",
  "Intro to Computer Science",
  "Software Design Studio",
  "Freshman Honors",
  "Honors Course",
  "Production Computer Graphics",
  "Operating Systems Design",
  "Social Visualization",
  "Parallel Programming",
  "Computational Advertising",
  "Intro to Deep Learning",
  "Cloud Computing Applications",
  "Data Science & Analytics",
  "AI for Robot Manipulation",
  "Internet of Things",
  "Trustworthy Machine Learning",
  "Audio Computing Lab",
  "Reinforcement Learning",
  "Advanced Information Retrieval",
  "Data Mining Principles",
  "Advanced Distributed Systems",
  "Parallel Computer Architecture",
  "Advanced Computer Networks",
  "Numerical Methods for PDEs",
  "Randomized Algorithms",
  "Advanced Computer Vision",
  "Advanced Bayesian Modeling",
  "Deep Learning for Healthcare",
  "Probabilistic Graphical Models",
  "HCI for ML",
  "US Border Lit and Cultures",
  "Indian Cinema in Context",
  "Modern Masterpieces West Cultr",
  "Chinese Thought and Culture",
  "Intro to Korea Through Film",
  "Probability in Engineering Lab",
  "ECE Technology & Management",
  "Biosensors",
  "Image & Video Processing",
  "Embedded DSP Laboratory",
  "Intro to VLSI System Design",
  "Mobile Computing & Application",
  "Wireless Networks",
  "Nanotechnology",
  "Analog IC Design",
  "Principles of Safe Autonomy",
  "IoT and Cognitive Computing",
  "Statistical Learning Theory",
  "Principles of Blockchains",
  "American Economic History",
  "Public Sector Economics",
  "Urban Economics",
  "Economics of the Workplace",
  "Employee Comp & Incentives",
  "Econ of Innovation and Tech",
  "Numerical Methods in Economics",
  "International Finance",
  "Applied Machine Learning: Econ",
  "Economic Growth",
  "International Financial",
  "Monetary Policy",
  "Macroeconomics for Business",
  "Econometric Analysis II",
  "Advanced Student Seminar",
  "Intro to TESL Methodology",
  "Principles of Language Testing",
  "Phon for Second Lang Teachers",
  "Grainger Engr: Designed by You",
  "Intro to British Literature",
  "Shakespeare on Film",
  "19th-Century American Fiction",
  "LGBT Literature and Film",
  "Documenting America",
  "Descriptive English Grammar",
  "Milton",
  "Topics in British Romantic Lit",
  "Jane Austen and Feminism",
  "Lit of American Minorities",
  "Renewable & Alternative Energy",
  "Tools for Sustainability",
  "Diversity in Higher Education",
  "Global Issues in Learning",
  "Race and Cultural Diversity",
  "History of American Education",
  "Historical and Social Barriers",
  "School and Society",
  "Global Youth and Citizenship",
  "Assessment for Learning",
  "Int. to Qual Methods",
  "Survey Methods",
  "Applied Regression Analysis",
  "Environmental Issues Today",
  "Environmental Writing",
  "Artsful Teaching through Integ",
  "Legal Issues in Real Estate",
  "Banking and Financial Reg",
  "Applied Financial Analysis",
  "Entrepreneurship Thru Acquistn",
  "Financial Risk Management",
  "Financial Data Mgt. & Analysis",
  "Corporate Finance I & II",
  "Math for Food Science",
  "Nutritional Physiology II",
  "Raw Materials for Processing",
  "Nutrition and the Life Cycle",
  "Communication in Nutrition",
  "Biochemical Nutrition II",
  "Nutrition Assessment & Therapy",
  "Food & Industrial Microbiology",
  "Applied Food Microbiology",
  "Food Processing Unit Ops I",
  "Food Processing Unit Ops I Lab",
  "Water Relations in Foods",
  "Earth's Physical Systems",
  "Cities of the World",
  "American People, Places, & Env",
  "Sustainability and the City",
  "Spatial Analysis",
  "Programming for GIS",
  "Geospatial AI & Mach. Learning",
  "Planet Earth",
  "Geology of the National Parks",
  "Emergence of Life",
  "Introduction to Hydrogeology",
  "Representing the Holocaust",
  "Intro Global Markets & Society",
  "Mass Incarceration",
  "Global Health: Policy & Govern",
  "Int Diplomacy and Negotiation",
  "Poverty Interventions and Eval",
  "Prep for 21st Cent Challenges",
  "College Academic Success",
  "Sexualities",
  "Gender in Gaming",
  "Feminist and Queer Activisms",
  "Film, TV, and Gender",
  "Feminist & Gender Theory",
  "Fairy Tales & Gender Formation",
  "Early Childhood Curriculum Dev",
  "Middle Childhood",
  "US Latina and Latino Families",
  "Hospitalized Children",
  "Inequality Public Pol & US Fam",
  "Family Conflict Management",
  "History of Islamic Middle East",
  "Western Civ to 1660",
  "Intro Hist Interpretation",
  "American Environmental History",
  "History of Southern Africa",
  "Modern China",
  "History of Ancient Rome",
  "Warfare Milit Insts & Soc",
  "20thC World from Midcentury",
  "Afro-American History to 1877",
  "Caribbean Latina/o Migration",
  "African-American Women",
  "Topics in Film and History",
  "Global History of Intelligence",
  "Middle East Since World War I",
  "Early Modern British Isles",
  "Modern Balkans thru Lit & Film",
  "History of Western Medicine",
  "The American Revolution",
  "Civil War and Reconstruction",
  "Urban History",
  "Introduction to Horticulture",
  "Medicinal Plants and Herbology",
  "Greenhouse Mgmt and Production",
  "Children and Nature",
  "Facilitation Skills",
  "Organization Development",
  "Strategic HRD",
  "Adult & Professional Education",
  "eLearning Ecologies",
  "Introduction to Plant Biology",
  "Environmental Biology",
  "Organismal & Evol Biol Lab",
  "Physiology",
  "Evolution",
  "Animal Behavior",
  "Plant Systematics",
  "Ecology and Human Health",
  "Evol of Traits and Genomes",
  "Plant Physiology",
  "Genes and Behavior",
  "Critical Eval Herbal Remedies",
  "Conservation Biology",
  "Community Ecology",
  "Industrial Quality Control",
  "Human Factors",
  "Production Planning & Control",
  "Stochastic Processes & Applic",
  "Simulation",
  "Financial Engineering",
  "Convex Optimization",
  "Stochastics & Numerics in Fin",
  "Deep Learning",
  "Electronic Trading",
  "Health Disparities in the U.S.",
  "Field Experience in i-Health",
  "Little Bits to Big Ideas",
  "Top Down Video Game Design",
  "The Video Game Dev Process",
  "Data, Machines and the Python",
  "Usable Privacy and Security",
  "Web Devel Using App Framwrk",
  "Sociotechnical Info Systems",
  "Digital Libraries",
  "Appd Machine Learn: Team Proj",
  "Metadata in Theory & Practice",
  "Social Crisis andLibrarianship",
  "Multimedia Reporting",
  "Research Methods in Journalism",
  "Navigating the Job Market",
  "Sport Jrn: Brundage & Olympics",
  "Development Activities",
  "Walking & Movement Wellness",
  "Injuries in Sport",
  "Body, Culture & Society",
  "Psychophysiology in Ex & Sport",
  "Rehabilitation Biomechanics",
  "Assistive Technologies",
  "Health Behaviors & Cognition",
  "History of the Prison",
  "Environmental Site Analysis",
  "Design Communications II",
  "History of World Landscapes",
  "Sustainable Design Principles",
  "Transfer Advantage",
  "Global Perspectives Pre-Prof S",
  "Life in the Andes",
  "Living the Law",
  "Constitutional Law I",
  "Introduction to Advocacy",
  "Administrative Law",
  "Secured Transactions",
  "White Collar Crime (ONL)",
  "Elder Law",
  "Criminal Proc: Adjudication",
  "Remedies",
  "Law and Psychology",
  "Race, Society, & the Law",
  "Mergers & Acquisitions",
  "Training and Development",
  "Leading Prof Orgs & Comm",
  "Collective Bargaining",
  "Negotiation in HR Decisions",
  "Infl, Chng & Politics in Org",
  "Negotiation Prin in HR Context",
  "Successful Change Mgmt",
  "Talent Management",
  "Elements of Phonology",
  "Intro to Computational Ling",
  "Criminalization and Punishment",
  "Sportsmedia Technology Culture",
  "Film Theory and Criticism",
  "Screenwriting",
  "Documentary and Music Culture",
  "Elementary Mathematics",
  "Calculus for Business I",
  "Non Euclidean Geometry",
  "Mathematical Logic",
  "Intro to Abstract Algebra",
  "Intro Partial Diff Equations",
  "Elementary Theory of Numbers",
  "Nonlinear Programming",
  "Quantum Channels I",
  "Marketing in a Digital World",
  "Global Strategy",
  "Strategic Innovation",
  "Intro to Bus Analytics w/R",
  "Human Anatomy & Physiology II",
  "Human Anat & Physiol Lab II",
  "Molecular Genetics",
  "Genetics and Genomics",
  "Mechanisms of Human Disease",
  "Eukaryotic Cell Biology Lab",
  "Sys & Integrative Physiology",
  "Gene Expression & Regulation",
  "Dev Bio, Stem Cells, Regen Med",
  "Microbial Biochemistry",
  "Bacterial Pathogenesis",
  "Evolution of InfectiousDisease",
  "Integrative Neuroscience",
  "Human Metabolic Disease",
  "Eukaryotic Cell Signaling",
  "Watching the Environment",
  "Design Projects-DES",
  "Energy Conversion Systems",
  "Numerical Thermo-Fluid Mechs",
  "Whole-Body Musculoskel Biomech",
  "Mechanobiology",
  "Mechanics for MatSE",
  "Electronic Properties of Matls",
  "Materials Laboratory II",
  "Kinetic Processes in Materials",
  "Microstructure Determination",
  "Ceramic Materials & Properties",
  "Polymer Science & Engineering",
  "Polymer Physics",
  "Electronic Materials I",
  "Biomolecular Materials Science",
  "Biomaterials and Nanomedicine",
  "Electron Microscopy",
  "Materials for Nanotechnology",
  "Modern Methods in Mat'ls Chara",
  "Music Theory and Practice II",
  "Introd Art Mus: Intl Perspect",
  "Music Then and Now",
  "Orientation Mus Tchg Lrng K-HS",
  "Social Foundations of Music Ed",
  "The History of Music II",
  "Analysis of Musical Form",
  "Music and Society",
  "Assessment/Eval in Music Ed",
  "Men's Glee Club",
  "Wind Orchestra",
  "The World Through Museums",
  "Introduction to Energy Sources",
  "Plasma and Fusion Science",
  "Radiation Interact w/Matter II",
  "Fuel Cells & Hydrogen Sources",
  "Wind Power Systems",
  "Energy and Security",
  "Wildlife Conservation",
  "Climate Change and Ecosystems",
  "Urban Ecology and Agriculture",
  "Environment and Society",
  "Natural Resource Policy Mgmt",
  "Ecology of Invasive Species",
  "Wildlife Population Ecology",
  "US Environ, Justic & Policy",
  "Integrative Ecosystem Mgmt",
  "Soil and Water Conservation",
  "Soil Fertility and Fertilizers",
  "Regulation of Metabolism",
  "Minds & Machines",
  "Theory of Knowledge",
  "Phil of Law and of the State",
  "Advanced Symbolic Logic",
  "Soph/Junr Special Topics Phys",
  "Condensed Matter Physics",
  "Statistical Physics",
  "Condensed Matter Physics I",
  "Drones and Asymmetric Warfare",
  "Intro to Pol Research",
  "The US Constitution II",
  "The US Supreme Court",
  "Interests Grps & Soc Movements",
  "Gov & Pol of China",
  "Gov & Pol of Middle East",
  "Justice in the Law",
  "Modern Political Theory",
  "Politics of the European Union",
  "Strategic Interntl Relations",
  "Stereotypes & Discrimination",
  "Applied Neuroscience",
  "Psych of the Infant",
  "Psychology of Gender",
  "Social Psych Methods Lab",
  "Topics in Clin/Comm Psych",
  "Clinical/Abnormal Psych Lab",
  "Cognitive Neuroscience",
  "Psychopharmacology",
  "Brain, Learning, and Memory",
  "Organizational Psych",
  "Restorative Justice",
  "Statistical Methods II",
  "Work and Disability",
  "Religion & Society in West II",
  "Zen",
  "Cultures & Lits of South Asia",
  "The Qur'an (Koran)",
  "Introduction to Hinduism",
  "Introduction to Buddhism",
  "E-Sport Foundations",
  "SPORT AND THE BIG TEN",
  "Finance in RST",
  "Sport Brand Management",
  "Tourism and Culture",
  "Strategic Management in RST",
  "Russia and Black America",
  "Managing Projects & Teams",
  "Measurement and Evaluation",
  "Vikings to Volvos: Scandinavia",
  "Engineering Graphics & Design",
  "Engineering Design Analysis",
  "Instrumentation and Test Lab",
  "Reliability Engineering",
  "Engrg Design Optimization",
  "Robot Dynamics and Control",
  "Mechatronics",
  "State Space Design for Control",
  "General Phonetics",
  "Intro Sound & Hearing Science",
  "Communication and Aging",
  "General Speech Science",
  "Hearing Health and Society",
  "Comm Competence and Disorders",
  "Evidence-Based Practice in CSD",
  "Stuttering: Theory & Practice",
  "Language and the Brain",
  "Augmentative & Alt Comm",
  "Asst & Mgmt of Dysphagia",
  "Social Organization",
  "Intro US Law & Legal Instit",
  "Soc of Political Polarization",
  "Social Inequality",
  "Criminal Justice System",
  "Senior Honors Seminar",
  "Social Entre & Social Change",
  "SW & Disability Studies",
  "Practice II",
  "SW Case Mngt Prac",
  "SW Practice with Indiv and Fam",
  "School Social Work Practice",
  "Intg Health Care Pol and Svcs",
  "Public School Policy/Services",
  "Clinical Research Seminar",
  "Integrated Behav. Health & HC",
  "Elementary Spanish I",
  "Bodies out of Place",
  "The Sounds of Spanish",
  "Bilingualism",
  "Sp Migrations Lit & Culture",
  "Modern Spanish Lit & Cultures",
  "Spanish Cultural Studies II",
  "Mexican Cinema",
  "Intro Intellectual Disability",
  "Instructional Strategies II",
  "Curriculum Development III",
  "Actuarial Statistics I",
  "Applied Regression and Design",
  "Sampling and Categorical Data",
  "Statistical Consulting",
  "Science Data",
  "Stochastic Processes",
  "Advanced Data Analysis",
  "Data Science Foundations",
  "Mathematical Statistics I",
  "Large Sample Theory",
  "High-Dimensional Statistics",
  "Intermediate Dynamics",
  "Continuum Mechanics",
  "Mathematical Methods II",
  "Intro to ILEE",
  "City Scholars",
  "Foundations: Theory + Practice",
  "Fundamentals of Acting II",
  "Literature of Modern Theatre",
  "History of Theatre II",
  "Wiring, Motors and Control Sys",
  "Residential Housing Design",
  "Ag Safety-Injury Prevention",
  "Urban Informatics I",
  "Cities in a Global Perspective",
  "Planning in Action",
  "Chicago: Planning & Urban Life",
  "Local Planning, Gov't and Law",
  "Urban Informatics II",
  "Pedestrian/Bicycle Planning",
  "Structure and Function II",
  "Structure and Function III",
  "Pathobiology III",
  "Medicine and Surgery III",
  "Ethics",
  "Multistate Taxation",
  "Special Research Problems",
  "Prof Soft Skills I",
  "Introduction to Modern Africa",
  "Food, Culture, and Society",
  "Understanding Visual Culture",
  "Technology Practicum",
  "DataStorytelling&Visualization",
  "Global Business Capstone",
  "American Race and Ethiniciy Cl",
  "Health Comm Research Methods I",
  "Health Comm Research MethodsII",
  "Intro to Comp Sci II",
  "Cloud Capstone",
  "Data Mining Capstone",
  "Intro to Diversity & Equity",
  "Technology &Educational Reform",
  "Sociology of Education",
  "Politics of Education",
  "Adult Learning and Development",
  "Genomics and Human Health",
  "Teen Materials",
  "Theory & Prct of Data Cleaning",
  "Cataloging for School Libs",
  "Government Regulation",
  "Economics of Human Resources",
  "Fundamentals of Business & Man",
  "Probability Theory",
  "Digital Marketing Analytics",
  "Global Business Horizons",
  "Fostering Creative Thinking",
  "Intro to Bus Analyt: CommData",
  "Data Toolkit",
  "Infonomics",
  "History of Rock",
  "Environmental Psychology",
  "Special Problems",
  "Promotional Strategy",
  "Strategic Media Management",
  "Introduction to Poverty",
  "Generalist SW Practice Methods",
  "Intl SW & Development",
  "Behav and Cogn Methods for SW",
  "Managing Human Service Orgs",
  "BHWELL Field Seminar",
  "Intermediate Spanish",
  "Intro to Spanish Grammar",
  "Spanish in the Professions",
  "Spanish Composition",
  "Disability Issues in SPED",
  "Statistical Modeling in R",
  "Experience & Meaning in Design",
];

const RESIDENCES = [
  "ISR",
  "Snyder",
  "Wassaja",
  "Scott",
  "Hopkins",
  "Nugent",
  "Weston",
  "Bousfield",
  "Suites at Third",
  "Skyline Tower",
  "The Dean",
  "The HERE",
  "309 Green",
  "FAR",
  "PAR",
  "Tower at Third",
];

const Register = (props) => {
  const boxWidth = "75%";

  const [loggedIn, setLoggedIn] = useState(false);
  const [failedRegistration, setFailedRegistration] = useState(false);
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [major, setMajor] = useState("");
  const [interests, setInterests] = useState([]);
  const [residence, setResidence] = useState("");
  const [RSOs, setRSOs] = useState([]);
  const [currentClasses, setCurrentClasses] = useState([]);
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");

  useEffect(() => {
    const status = window.localStorage.getItem("token");
    setLoggedIn(status != null);
  }, []);

  const handleFirstNameChange = (e) => {
    setFirstName(e.target.value);
  };

  const handleLastNameChange = (e) => {
    setLastName(e.target.value);
  };

  const handleMajorChange = (e) => {
    setMajor(e.target.value);
  };

  const handleInterestsChange = (e) => {
    setInterests(e.target.value);
  };

  const handleResidenceChange = (e) => {
    setResidence(e.target.value);
  };

  const handleRSOChange = (e) => {
    setRSOs(e.target.value);
  };

  const handleClassesChange = (e) => {
    setCurrentClasses(e.target.value);
  };

  const handleUsernameChange = (e) => {
    setUsername(e.target.value);
  };

  const handlePasswordChange = (e) => {
    setPassword(e.target.value);
  };

  const onSubmit = async () => {
    // Make a post request to the database, create new user with info
    const majorId = MAJORS.indexOf(major);
    const interestIds = [];
    console.log(interests);
    for (let ix = 0; ix < interests.length; ++ix) {
      interestIds.push(interests.indexOf(interests[ix]));
    }
    console.log(RSOs);
    const rsoIds = [];
    for (let ix = 0; ix < RSOs.length; ++ix) {
      rsoIds.push(RSOList.indexOf(RSOs[ix]));
    }


    let courses = "";
    for (let ix = 0; ix < currentClasses.length; ++ix) {
      if (ix != currentClasses.length - 1) {
        courses += currentClasses[ix] + ", ";
      } else {
        courses += currentClasses[ix];
      }
    }

    const data = {
      username: username,
      password: password,
      firstName: firstName,
      lastName: lastName,
      majorID: majorId,
      currentClasses: courses,
      interestIDs: interestIds,
      rsoIDs: rsoIds,
      residence: residence,
    };

    console.log(data);
    // Update database
    try {
      const response = await fetch("http://127.0.0.1:5000/register", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(data),
      });
      if (response.status == 200) {
        const data = await response.json();
        if (data.successful) {
          window.localStorage.setItem("token", username);
          setLoggedIn(true);
          window.location.assign('/home'); //new
        }
      } else {
        setFailedRegistration(true);
      }
    } catch (e) {
      console.log(e);
    }
  };

  return loggedIn ? (
    <Home />
  ) : (
    <div className="centered">
      <Stack
        color="#E84A27"
        spacing={3}
        sx={{
          borderRadius: 3,
          boxShadow: 5,
          alignItems: "center",
          backgroundColor: "#EDE9E8",
        }}
        p={6}
      >
        <div className="register-meet">
          <Typography variant="h3">Register - Match and Meet</Typography>
        </div>
        <TextField
          id="outlined-basic"
          label="First Name"
          size="small"
          sx={{ width: boxWidth }}
          value={firstName}
          onChange={handleFirstNameChange}
        />
        <TextField
          id="outlined-basic"
          label="Last Name"
          size="small"
          sx={{ width: boxWidth }}
          value={lastName}
          onChange={handleLastNameChange}
        />
        <FormControl sx={{ width: boxWidth }}>
          <InputLabel id="major-select">Major</InputLabel>
          <Select
            labelId="major-select"
            id="major-select"
            value={major}
            label="Major"
            onChange={handleMajorChange}
          >
            {MAJORS.map((majorItem, index) => {
              return (
                <MenuItem key={index} value={majorItem}>
                  {majorItem}
                </MenuItem>
              );
            })}
          </Select>
        </FormControl>
        <FormControl sx={{ width: boxWidth }}>
          <InputLabel id="residence-select">Residence</InputLabel>
          <Select
            labelId="residence-select"
            id="residence-select"
            value={residence}
            label="Residence"
            onChange={handleResidenceChange}
          >
            {RESIDENCES.map((residenceItem, index) => {
              return (
                <MenuItem key={index} value={residenceItem}>
                  {residenceItem}
                </MenuItem>
              );
            })}
          </Select>
        </FormControl>
        <FormControl sx={{ width: boxWidth }}>
          <InputLabel id="interest-select">Interests</InputLabel>
          <Select
            labelId="interest-select"
            id="interest-select"
            multiple
            value={interests}
            label="Interests"
            onChange={handleInterestsChange}
            input={<OutlinedInput id="select-multiple-chip" label="Chip" />}
            renderValue={(selected) => (
              <Box sx={{ display: "flex", flexWrap: "wrap", gap: 0.5 }}>
                {selected.map((value) => (
                  <Chip key={value} label={value} />
                ))}
              </Box>
            )}
          >
            {INTERESTS.map((interest, index) => {
              return (
                <MenuItem key={index} value={interest}>
                  {interest}
                </MenuItem>
              );
            })}
          </Select>
        </FormControl>
        <FormControl sx={{ width: boxWidth }}>
          <InputLabel id="rso-select">RSOs</InputLabel>
          <Select
            labelId="rso-select"
            id="rso-select"
            multiple
            value={RSOs}
            label="RSOs"
            onChange={handleRSOChange}
            input={<OutlinedInput id="select-multiple-chip" label="Chip" />}
            renderValue={(selected) => (
              <Box sx={{ display: "flex", flexWrap: "wrap", gap: 0.5 }}>
                {selected.map((value) => (
                  <Chip key={value} label={value} />
                ))}
              </Box>
            )}
          >
            {RSOList.map((RSO, index) => {
              return (
                <MenuItem key={index} value={RSO}>
                  {RSO}
                </MenuItem>
              );
            })}
          </Select>
        </FormControl>
        <FormControl sx={{ width: boxWidth }}>
          <InputLabel id="classes-select">Current Classes</InputLabel>
          <Select
            labelId="classes-select"
            id="classes-select"
            multiple
            value={currentClasses}
            label="Current Classes"
            onChange={handleClassesChange}
            input={<OutlinedInput id="select-multiple-chip" label="Chip" />}
            renderValue={(selected) => (
              <Box sx={{ display: "flex", flexWrap: "wrap", gap: 0.5 }}>
                {selected.map((value) => (
                  <Chip key={value} label={value} />
                ))}
              </Box>
            )}
          >
            {CLASSES.map((classes, index) => {
              return (
                <MenuItem key={index} value={classes}>
                  {classes}
                </MenuItem>
              );
            })}
          </Select>
        </FormControl>
        <TextField
          id="outlined-basic"
          label="Username"
          size="small"
          sx={{ width: boxWidth }}
          value={username}
          onChange={handleUsernameChange}
        />
        <TextField
          id="outlined-basic"
          label="Password"
          type="password"
          size="small"
          sx={{ width: boxWidth }}
          value={password}
          onChange={handlePasswordChange}
        />
        {failedRegistration && (
          <Alert
            severity="error"
            onClose={() => {
              setFailedRegistration(false);
            }}
            variant="filled"
          >
            Username already exists!
          </Alert>
        )}
        <Button onClick={onSubmit} variant="contained">
          Register
        </Button>
      </Stack>
    </div>
  );
};

export default Register;
